name: redesain_lazada
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Rectangle 3.png
    - assets/images/Rectangle 13.png
    - assets/images/Rectangle 14.png
    - assets/images/Rectangle 21.png
    - assets/images/Rectangle 23.png
    - assets/images/Rectangle 22.png


